pollapp/urls.py
from django.urls import path

from pollapp import views

app_name = 'basic_app'

urlpatterns = [
    path('register/',views.register,name='register'),

]

schools/urls.py
from django.urls import path

from . import views

app_name = 'schools'

urlpatterns = [
    path('indexpage/',views.index,name='index'),

]

servayapp/urls.py
from django.urls import path

from servayapp import views

app_name = 'poll_app'


urlpatterns = [
    path('',views.index,name='index'),
    path('polling_page',views.polling,name='polling')
]

untitled/urls.py
from django.contrib import admin
from django.urls import path, include
from pollapp import views as pollappview
from untitled import settings
from django.conf.urls.static import static
import schools
urlpatterns = [
    path('',pollappview.index,name='index'),
    path('admin/', admin.site.urls),
    path('registration/',include('pollapp.urls')),
    path('poll_app/',include('servayapp.urls')),
    path('contact-us',pollappview.contact_us,name='contact_us'),
    path('about-us',pollappview.about_us,name='about_us'),
    path('schools/',include('schools.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pollapp/models.py
from django.db import models
from django.contrib.auth.admin import User

# Create your models here.

class UserProfileInfo(models.Model):

    # Don't Inherit from User
    user = models.OneToOneField(User,on_delete='delete')

    # Addtional Attribute

    picture = models.ImageField(upload_to='profile_pics')

    def __str__(self):
        return self.user.username

schools/models.py
from django.db import models

# Create your models here.

class School(models.Model):
    school = models.CharField(max_length=255,unique=True)

    def __str__(self):
        return self.school

class Subject(models.Model):
    school = models.ForeignKey(School,on_delete=True)
    subject = models.CharField(max_length=255,unique=True)

    def __str__(self):
        return self.subject
class ClassData(models.Model):
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE)
    class_number = models.IntegerField()
    class_size = models.IntegerField()

    def __str__(self):
        return str(self.class_number)

class ProfessorData(models.Model):
    classData = models.ForeignKey(ClassData,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(primary_key=True)

    def __str__(self):
        return self.last_name+", "+self.first_name

servayapp/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    topic_name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return (self.topic_name)


class Webpage(models.Model):
    topic = models.ForeignKey(Topic,on_delete=True)
    name = models.CharField(max_length=255,unique=True)
    url = models.URLField(unique=True)


    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage,on_delete=True)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

pollapp/forms.py
from django import forms
from django.contrib.auth.models import User

from pollapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    picture = forms.ImageField(required=False)

    class Meta():
        model = UserProfileInfo
        fields = ('picture',)

servayapp/forms.py
from django.forms import ModelForm
from django import forms
from servayapp.models import Webpage, Topic, AccessRecord


class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        fields = ('topic_name',)


class WebpageForm(forms.ModelForm):

    class Meta:
        model = Webpage
        fields = ('topic', 'name', 'url')

class AccessRecord(forms.ModelForm):

    class Meta:
        model = AccessRecord
        fields = ('name','date')

pollapp/views.py
from django.shortcuts import render

# Create your views here.
from pollapp.forms import UserForm, UserProfileInfoForm


def index(request):
    return render(request, 'firstapp/index.html')

def register(request):

    registered = False

    if request.method =='POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)

            user.save()

            profile = profile_form.save(commit=False)

            profile.user = user
            print(request.FILES)
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']


            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    data_dict = {
        'user_form':user_form,
        'profile_form':profile_form,
        'registered':registered
    }

    return render(request, 'firstapp/registration.html', data_dict)


def about_us(request):
    return render(request,'about.html')

def contact_us(request):
    return render(request,'contact.html')

schools/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render
from .somewhere import SortHeaders
# Create your views here.
from schools.models import ProfessorData

LIST_HEADERS = (
    ("SChoool",None),
    ('Subject',None),
    ('Class Number',None),
    ('Class Size', None),
    ('First Name', 'first_name'),
    ('Last Name', 'last_name'),
    ('Email', None),
)
def index(request):
    user_list = ProfessorData.objects.all()
    page = request.GET.get('page', 1)
    order = request.GET.get('sort','school')
    print(order)

    paginator = Paginator(user_list, 10)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    return render(request,'schools/index.html',context={ 'users': users })

servayapp/views.py
from django.shortcuts import render

# Create your views here.
from servayapp.forms import TopicForm, WebpageForm


def index(request):
    return render(request, 'servayapp/index.html')

def polling(request):

    accepted = False

    if request.method == "POST":
        print("done")
    else:
        mydict = {
            'Topic': TopicForm(),
            'webpage': WebpageForm()
        }
        return render(request,'servayapp/question1.html',mydict)

templates/about.html
{% extends 'template.html' %}

{% block titleblock %}
About US
{% endblock %}
{% block bodyblock %}

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
            </div>
        </div>
    </div>

    <hr>
{% endblock %}

templates/contact.html
{% extends 'template.html' %}
{% block titleblock %}
Contact Us
{% endblock %}
{% block bodyblock %}

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Name</label>
                            <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Email Address</label>
                            <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Phone Number</label>
                            <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Message</label>
                            <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <hr>

{% endblock %}

templates/firstapp/index.html
{% extends "template.html" %}
{% load staticfiles %}
{% load static %}
{% block titleblock %}
My First Site
{% endblock %}
{% block bodyblock %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview">
                    <a href="../post.html">
                        <h2 class="post-title">
                            Man must explore, and this is exploration at its greatest
                        </h2>
                        <h3 class="post-subtitle">
                            Problems look mighty small from 150 miles up
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on September 24, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="../post.html">
                        <h2 class="post-title">
                            I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
                        </h2>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on September 18, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="../post.html">
                        <h2 class="post-title">
                            Science has not yet mastered prophecy
                        </h2>
                        <h3 class="post-subtitle">
                            We predict too much for the next year and yet far too little for the next ten.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on August 24, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="../post.html">
                        <h2 class="post-title">
                            Failure is not an option
                        </h2>
                        <h3 class="post-subtitle">
                            Many say exploration is part of our destiny, but it’s actually our duty to future generations.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on July 8, 2014</p>
                </div>
                <hr>
                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="#">Older Posts &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <hr>

{% endblock %}

templates/firstapp/registration.html
{% extends 'template.html' %}
{% load staticfiles %}
{% block titleblock %}
Login Page
{% endblock %}
{% block bodyblock %}
 <div>
 {% if registered %}
    <h1> Thank You For Registering!</h1>
     {% else %}
     <h1> Register Here!</h1>
     <h3>Fill out the Form</h3>

     <form method = "post" enctype="multipart/form-data">
     {% csrf_token %}
     {{ user_form.as_p }}
     {{ profile_form.as_p }}
     <input type="submit" name="" value="Register">
     </form>
 {% endif %}
 </div>
{% endblock %}

templates/index.html
{% extends "template.html" %}
{% load staticfiles %}
{% load static %}
{% block titleblock %}
My First Site
{% endblock %}
{% block bodyblock %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Man must explore, and this is exploration at its greatest
                        </h2>
                        <h3 class="post-subtitle">
                            Problems look mighty small from 150 miles up
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on September 24, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
                        </h2>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on September 18, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Science has not yet mastered prophecy
                        </h2>
                        <h3 class="post-subtitle">
                            We predict too much for the next year and yet far too little for the next ten.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on August 24, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Failure is not an option
                        </h2>
                        <h3 class="post-subtitle">
                            Many say exploration is part of our destiny, but it’s actually our duty to future generations.
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on July 8, 2014</p>
                </div>
                <hr>
                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="#">Older Posts &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <hr>

{% endblock %}

templates/schools/index.html
{% extends 'template.html' %}
{% load staticfiles %}

{% block titleblock %}
Schools Data
{% endblock %}

{% block bodyblock %}
<h1>Congrats You Landed on School Page</h1>
<h3>Here Is Some Data</h3>
    {% if users %}
        <table class="table table-hover" style="border: 1px solid black;text-align: center;width: 100%">
        <thead class="thead-dark" style="text-align: center">
        <th href="#" onclick="changeurl('school')">School</th>
        <th href="#" onclick="changeurl('subject')">Subject</th>
        <th href="#" onclick="changeurl('classsize')">class size</th>
        <th href="#" onclick="changeurl('classnumber')">class Number</th>
        <th href="#" onclick="changeurl('first_name')">First Name</th>
        <th href="#" onclick="changeurl('last_name')">Last Name</th>
        <th href="#" onclick="changeurl('email')">Email</th>
        </thead>
        {% for i in users %}
        <tr>
            <td>{{ i.classData.subject.school.school }}</td>
            <td>{{ i.classData.subject.subject }}</td>
            <td>{{ i.classData.class_size }}</td>
            <td>{{ i.classData.class_number }}</td>
            <td>{{ i.first_name }}</td>
            <td>    {{ i.last_name }}</td>
            <td>    <code>{{   i.email }}</code></td>
            </p>
        </tr>
        {% endfor %}
</table>

    {% endif %}

  {% if users.has_other_pages %}
  <ul class="pagination">
    {% if users.has_previous %}
      <li><a href="?page={{ users.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in users.paginator.page_range %}
      {% if users.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if users.has_next %}
      <li><a href="?page={{ users.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

    <script type="text/javascript">
    function changeurl(name) {
        window.location = window.location+"&sort="+name;
    }
    </script>
    <style>
    th:hover{
        background-color: #9d9d9d;
    }
    </style>
{% endblock %}

templates/servayapp/index.html
{% extends 'template.html' %}
{% block titleblock %}
Questions
{% endblock %}

{% block bodyblock %}
<div class="carousel-inner -align-justify -arrow-circle-o-down">
<span>
    <h2 style=""> Hello This is My Poll App Index Page.</h2>
</span>
<a href="{% url 'poll_app:polling' %}">Go to servey Page</a>
</div>
{% endblock %}

templates/servayapp/question1.html
{% extends 'template.html' %}
{% load staticfiles %}

{% block titleblock %}
Servay
{% endblock %}

{% block bodyblock %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ Topic.as_p }}
    <input type="submit" value="register">
    </form>

<h2> Hello if you don't added a topic then use the above Section</h2>
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ Topic.as_p }}
    {{ webpage.as_p }}
    <input type="submit" value="register">
    </form>

{% endblock %}

templates/template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block titleblock %}{% endblock %} </title>
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
 <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}">Home</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">

                    <li>
                        <a href="{% url 'about_us' %}">About</a>
                    </li>
                      <li>
                        <a href="{% url 'contact_us' %}">Contact Us</a>

                    </li>
                    <li>
                        <a href="{% url 'schools:index' %}">School Info</a>
                    </li>
                    <li>
                        <a href="{% url 'poll_app:index' %}">Second App</a>
                    </li>
                    <li>
                        <a href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li>
                        <a href="{% url 'basic_app:register' %}">Login</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('{% static 'img/home-bg.jpg' %}') ">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Clean Blog</h1>
                        <hr class="small">
                        <span class="subheading">A Clean Blog Theme by Start Bootstrap</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% block bodyblock %}
{% endblock %}
<!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
                </div>
            </div>
        </div>
    </footer>

 <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>
</html>